<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title><?php echo $params['title'] ?>$</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
    <div class="content">
        <main class="container">
            <?php echo $params['body'] ?>
        </main>
    </div>
</body>
</html>
